# Generated by Django 4.2.3 on 2023-08-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=15)),
                ('end_date', models.CharField(max_length=15)),
                ('sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('sum', models.IntegerField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.credit')),
            ],
        ),
    ]
