# Generated by Django 4.2.3 on 2024-06-20 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Командир',
                'verbose_name_plural': 'Командири',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('phone2', models.CharField(max_length=60)),
                ('dr', models.CharField(max_length=60)),
                ('addres', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Курсант',
                'verbose_name_plural': 'Курсанти',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Локація',
                'verbose_name_plural': 'Локації',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Рота',
                'verbose_name_plural': 'Роти',
            },
        ),
        migrations.CreateModel(
            name='Vzvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rota')),
            ],
            options={
                'verbose_name': 'Взвод',
                'verbose_name_plural': 'Взводи',
            },
        ),
        migrations.CreateModel(
            name='Position2Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='docs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.instructor')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.position')),
            ],
            options={
                'verbose_name': 'Пересування',
                'verbose_name_plural': 'Пересування',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.position'),
        ),
        migrations.AddField(
            model_name='person',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rota'),
        ),
        migrations.AddField(
            model_name='person',
            name='vzvod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vzvod'),
        ),
    ]
