# Generated by Django 4.2.3 on 2024-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Командир', 'verbose_name_plural': 'Командири'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Курсант', 'verbose_name_plural': 'Курсанти'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Локація', 'verbose_name_plural': 'Локації'},
        ),
        migrations.AlterModelOptions(
            name='position2person',
            options={'verbose_name': 'Пересування', 'verbose_name_plural': 'Пересування'},
        ),
        migrations.AlterModelOptions(
            name='rota',
            options={'verbose_name': 'Рота', 'verbose_name_plural': 'Роти'},
        ),
        migrations.AlterModelOptions(
            name='vzvod',
            options={'verbose_name': 'Взвод', 'verbose_name_plural': 'Взводи'},
        ),
        migrations.AddField(
            model_name='position2person',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
